/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 appdev.gltf --transform
Author: DailyArt (https://sketchfab.com/D.art)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/huawei-p40-pro-9a89d735bd074ae796946bd942464874
Title: huawei p40 pro
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./img/appdev-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_6.geometry} material={materials.shouji} position={[-771.153, 195.272, 103.762]} scale={79.96} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.BOLI} position={[-771.153, 195.272, 103.762]} scale={79.96} />
    </group>
  )
}

useGLTF.preload('/appdev-transformed.glb')
