/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 appdev.gltf --transform
Author: iSteven (https://sketchfab.com/OneSteven)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/iphone-14-pro-c14aa19d45674948bda936d9d3de744b
Title: iPhone 14 Pro
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./img/appdev-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_aple_0.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh001_buton_0.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh007_screen_0.geometry} material={materials.screen} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh009_cam_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh015_glass_0.geometry} material={materials.PaletteMaterial003} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.mesh017_glass_flash_0.geometry} material={materials.PaletteMaterial004} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/appdev-transformed.glb')
