/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 blog.gltf --transform
Author: Francesco Coldesina (https://sketchfab.com/topfrank2013)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/typewriter-f8339a2f7ea849b8afbebb76a40e1759
Title: Typewriter
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./img/blog-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Neri_Royal_typewriter_Plastic_0.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Neri_Royal_typewriter_Buttons_0.geometry} material={materials.Royal_typewriter_Buttons} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Neri_Royal_typewriter_Paper_0.geometry} material={materials.Royal_typewriter_Paper} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Logo_Royal_typewriter_Label_0.geometry} material={materials.Royal_typewriter_Label} position={[0, 13.95, 11.371]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Bodymy01_17_-_Default_0'].geometry} material={materials['17_-_Default']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/blog-transformed.glb')
