/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 lantern.gltf --transform
Author: Skrisilence (https://sketchfab.com/skrisilence)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lantern-f5122e70efc3454cac3549c1a814d715
Title: Lantern
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./img/lantern-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.blinn3} />
    </group>
  )
}

useGLTF.preload('/lantern-transformed.glb')
