/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 uid.gltf --transform
Author: Diego G. (https://sketchfab.com/empty_mirror)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/diseno-3d-web-development-resource-70f8d9e0f9924450888232a7a6afa02d
Title: Diseño 3D - Web Development Resource
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./img/uid-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Cylinder002|Cone|Dupli|_Material004_0'].geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes['BezierCurve003|Cube017|Dupli|_Planta002_0'].geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes['BezierCurve003|Cube017|Dupli|_Planta003_0'].geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Cube002_Maceta_0.geometry} material={materials.PaletteMaterial001} position={[-0.272, -0.026, -0.025]} rotation={[0, 0.466, 0]} scale={0.001} />
      <mesh geometry={nodes.Laptop_Cristal_0.geometry} material={materials.Captura_de_pantalla_173} position={[0.029, 0.152, -0.06]} rotation={[0.087, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/uid-transformed.glb')
