/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 uxr.gltf --transform
Author: kyuukonneko (https://sketchfab.com/kyuukonneko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bulletin-board-e16dd24c375b4079b4e326a9101e331d
Title: Bulletin Board
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./img/uxr-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Line006_line_0.geometry} material={materials.line} position={[0.12, 0.393, 0.055]} scale={0.025} />
      <mesh geometry={nodes.Paper002_paper_2_0.geometry} material={materials.paper_2} position={[0.032, 0.397, 0.029]} rotation={[0, 0, 0.262]} scale={[0.013, 0.011, 0.017]} />
      <mesh geometry={nodes.Paper003_paper_3_0.geometry} material={materials.paper_3} position={[-0.825, 0.587, 0.029]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 0.014, 0.039]} />
      <mesh geometry={nodes.Paper001_paper_1_0.geometry} material={materials.paper_1} position={[-0.826, 0.221, 0.062]} rotation={[0, 0, -0.262]} scale={0.014} />
      <mesh geometry={nodes.Pin001_pin_0.geometry} material={materials.material} position={[-0.958, 0.528, 0.07]} scale={0.006} />
      <mesh geometry={nodes.Board001_board_0.geometry} material={materials.board} position={[0, 0.063, -0.104]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('/uxr-transformed.glb')
